spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
    properties:
      hiberante:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
