spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
    properties:
      hiberante:
        dialect: org.hibernate.dialect.MySQL57Dialect

  h2:
    console:
      enabled: true
  session:
    store-type: jdbc

